import { isIP } from "node:net";

/** go2rtc stays on loopback: it lets localhost callers in without auth, so only this agent process may talk to it. */
export const GO2RTC_LOOPBACK = {
  api: "127.0.0.1:1984",
  rtsp: "127.0.0.1:8554",
  webrtc: "127.0.0.1:8555",
} as const;

/** Config written to disk: listeners and auth only. Stream sources carry credentials and are pushed over the local API, in memory. */
export function buildGo2rtcConfig(): string {
  return [
    "# Generated by pantau-agent. go2rtc must never listen beyond loopback.",
    "api:",
    `  listen: "${GO2RTC_LOOPBACK.api}"`,
    "  local_auth: true",
    "rtsp:",
    `  listen: "${GO2RTC_LOOPBACK.rtsp}"`,
    "webrtc:",
    `  listen: "${GO2RTC_LOOPBACK.webrtc}"`,
    "",
  ].join("\n");
}

export function assertLoopbackUrl(raw: string): URL {
  let u: URL;
  try {
    u = new URL(raw);
  } catch {
    throw new Error("go2rtc base url is not a valid url");
  }
  const host = u.hostname.replace(/^\[|\]$/g, "");
  const loopback = (isIP(host) === 4 && host.startsWith("127.")) || host === "::1";
  if (u.protocol !== "http:" || !loopback || u.username || u.password) {
    throw new Error("go2rtc base url must be http on a loopback address without userinfo");
  }
  return u;
}

const STREAM_NAME = /^[A-Za-z0-9_-]{1,64}$/;

export interface Go2rtcOptions {
  baseUrl?: string;
  timeoutMs?: number;
}

export class Go2rtcClient {
  private readonly base: string;
  private readonly timeoutMs: number;

  constructor(opts: Go2rtcOptions = {}) {
    this.base = assertLoopbackUrl(opts.baseUrl ?? `http://${GO2RTC_LOOPBACK.api}`).origin;
    this.timeoutMs = opts.timeoutMs ?? 3000;
  }

  private async call(method: string, path: string, params: Record<string, string> = {}): Promise<Response> {
    const url = new URL(path, this.base);
    for (const [k, v] of Object.entries(params)) url.searchParams.set(k, v);
    let res: Response;
    try {
      res = await fetch(url, { method, signal: AbortSignal.timeout(this.timeoutMs), redirect: "error" });
    } catch {
      // the fetch error can embed the url, which holds the credential
      throw new Error("go2rtc is not reachable");
    }
    return res;
  }

  private name(n: string): string {
    if (!STREAM_NAME.test(n)) throw new Error("invalid stream name");
    return n;
  }

  /** Only rtsp(s) sources: go2rtc also accepts exec: and ffmpeg: sources, which run commands. */
  async putStream(name: string, src: string): Promise<void> {
    this.name(name);
    if (!/^rtsps?:\/\//i.test(src)) throw new Error("go2rtc source must be rtsp or rtsps");
    const res = await this.call("PUT", "/api/streams", { name, src });
    if (!res.ok) throw new Error(`go2rtc refused the stream (${res.status})`);
  }

  async deleteStream(name: string): Promise<void> {
    const res = await this.call("DELETE", "/api/streams", { name: this.name(name) });
    if (!res.ok && res.status !== 404) throw new Error(`go2rtc could not remove the stream (${res.status})`);
  }

  async listStreams(): Promise<string[]> {
    const res = await this.call("GET", "/api/streams");
    if (!res.ok) throw new Error(`go2rtc list failed (${res.status})`);
    return Object.keys((await res.json()) as Record<string, unknown>).sort();
  }

  async frame(name: string): Promise<Buffer> {
    const res = await this.call("GET", "/api/frame.jpeg", { src: this.name(name) });
    if (!res.ok) throw new Error(`go2rtc frame failed (${res.status})`);
    return Buffer.from(await res.arrayBuffer());
  }
}
